FROM python:3.10

RUN pip install boto3==1.34.8
RUN pip install psutil==5.9.7
RUN pip install torch==2.1.2
RUN pip install mlflow==2.9.2
RUN pip install pydantic==2.5.3
RUN pip install pydantic-settings==2.1.0
RUN pip install tqdm==4.66.1